"""
Unit tests for SAR PDF Generator.

Tests the generation of SAR PDF documents following FinCEN template layout.
"""

import pytest
from datetime import datetime, timezone
from io import BytesIO

from app.services.sar.pdf_generator import SARPDFGenerator
from app.schemas.sar import (
    SARData,
    FilingInstitution,
    SubjectInfo,
    ActivityInfo,
    SARReportLayout,
    SubjectInformationSection,
    ReportingInstitutionSection,
    SuspiciousActivitySection,
    NarrativeSection,
    TransactionInformationSection,
    SupportingDocumentationSection,
    InternalReviewActionsSection,
    LawEnforcementNotificationSection,
)


@pytest.fixture
def pdf_generator():
    """Create a SARPDFGenerator instance."""
    return SARPDFGenerator()


@pytest.fixture
def sample_filing_institution():
    """Create sample filing institution data."""
    return FilingInstitution(
        name="Test Bank",
        tin="12-3456789",
        address="123 Main St",
        city="New York",
        state="NY",
        zip_code="10001",
        contact_name="John Doe",
        contact_phone="555-0100",
        contact_email="john@testbank.com",
    )


@pytest.fixture
def sample_subject():
    """Create sample subject information."""
    return SubjectInfo(
        subject_type="Entity",
        name="Wallet 0x1234567...",
        address=None,
        identification="0x1234567890abcdef1234567890abcdef12345678",
        account_number=None,
        relationship_to_institution="Customer",
    )


@pytest.fixture
def sample_activity():
    """Create sample activity information."""
    return ActivityInfo(
        activity_date_from=datetime(2024, 1, 1, tzinfo=timezone.utc),
        activity_date_to=datetime(2024, 1, 31, tzinfo=timezone.utc),
        total_amount=50000.00,
        activity_type=["Money Laundering", "Structuring"],
        product_type=["Digital Currency"],
        instrument_type=["Blockchain Transaction"],
    )


@pytest.fixture
def sample_sar_data(sample_filing_institution, sample_subject, sample_activity):
    """Create complete sample SAR data."""
    report_layout = SARReportLayout(
        subject_information=SubjectInformationSection(
            full_name=sample_subject.name,
            address=sample_subject.address,
            identification_number=sample_subject.identification,
            occupation_or_business_type=sample_subject.subject_type,
        ),
        reporting_institution=ReportingInstitutionSection(
            institution_name=sample_filing_institution.name,
            branch_location=f"{sample_filing_institution.address}, {sample_filing_institution.city}",
            contact_person=sample_filing_institution.contact_name,
            contact_information=f"{sample_filing_institution.contact_phone} | {sample_filing_institution.contact_email}",
            institution_id=sample_filing_institution.tin,
        ),
        suspicious_activity=SuspiciousActivitySection(
            activity_dates=[
                sample_activity.activity_date_from.date(),
                sample_activity.activity_date_to.date(),
            ],
            activity_types=sample_activity.activity_type,
            total_amount=sample_activity.total_amount,
            affected_accounts=[sample_subject.identification],
        ),
        narrative=NarrativeSection(
            summary_text="This is a test narrative describing suspicious activity.",
        ),
        transaction_information=TransactionInformationSection(),
        supporting_documentation=SupportingDocumentationSection(),
        internal_review_actions=InternalReviewActionsSection(),
        law_enforcement_notification=LawEnforcementNotificationSection(),
    )
    return SARData(
        filing_institution=sample_filing_institution,
        subject=sample_subject,
        activity=sample_activity,
        narrative="This is a test narrative describing suspicious activity.",
        case_id="case-123",
        report_id="report-456",
        generated_at=datetime(2024, 2, 1, 12, 0, 0, tzinfo=timezone.utc),
        report_layout=report_layout,
    )


class TestCreateSARPDF:
    """Tests for create_sar_pdf method."""

    def test_returns_pdf_bytes(self, pdf_generator, sample_sar_data):
        """Test that PDF generation returns bytes."""
        result = pdf_generator.create_sar_pdf(sample_sar_data)

        assert isinstance(result, bytes)
        assert len(result) > 0

    def test_pdf_starts_with_pdf_header(self, pdf_generator, sample_sar_data):
        """Test that generated bytes start with PDF header."""
        result = pdf_generator.create_sar_pdf(sample_sar_data)

        # PDF files start with %PDF-
        assert result.startswith(b"%PDF-")

    def test_generates_valid_pdf_structure(self, pdf_generator, sample_sar_data):
        """Test that generated PDF has valid structure."""
        result = pdf_generator.create_sar_pdf(sample_sar_data)

        # Check for PDF EOF marker
        assert b"%%EOF" in result

    def test_handles_short_narrative(self, pdf_generator, sample_sar_data):
        """Test PDF generation with short narrative."""
        sample_sar_data.narrative = "Short narrative."
        
        result = pdf_generator.create_sar_pdf(sample_sar_data)

        assert isinstance(result, bytes)
        assert len(result) > 0

    def test_handles_long_narrative(self, pdf_generator, sample_sar_data):
        """Test PDF generation with long narrative that spans multiple pages."""
        # Create a long narrative (approximately 2000 words)
        long_narrative = " ".join(["This is a test sentence."] * 400)
        sample_sar_data.narrative = long_narrative
        
        result = pdf_generator.create_sar_pdf(sample_sar_data)

        assert isinstance(result, bytes)
        assert len(result) > 0
        # Longer narrative should produce larger PDF
        assert len(result) > 3000

    def test_handles_empty_narrative(self, pdf_generator, sample_sar_data):
        """Test PDF generation with empty narrative."""
        sample_sar_data.narrative = ""
        
        result = pdf_generator.create_sar_pdf(sample_sar_data)

        assert isinstance(result, bytes)
        assert len(result) > 0


class TestRenderHeaderSection:
    """Tests for render_header_section method."""

    def test_renders_filing_institution_name(self, pdf_generator, sample_sar_data):
        """Test that filing institution name is included in PDF."""
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import letter
        
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        y_position = letter[1] - 0.5 * 72  # Start position
        
        new_y = pdf_generator.render_header_section(c, sample_sar_data, y_position)
        
        # Y position should decrease after rendering
        assert new_y < y_position

    def test_includes_report_metadata(self, pdf_generator, sample_sar_data):
        """Test that report ID and case ID are rendered."""
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import letter
        
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        y_position = letter[1] - 0.5 * 72
        
        new_y = pdf_generator.render_header_section(c, sample_sar_data, y_position)
        
        # Should return updated position
        assert isinstance(new_y, float)
        assert new_y > 0


class TestRenderSubjectInformation:
    """Tests for render_subject_information method."""

    def test_renders_subject_type(self, pdf_generator, sample_subject):
        """Test that subject type is rendered."""
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import letter
        
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        y_position = 500
        
        new_y = pdf_generator.render_subject_information(c, sample_subject, y_position)
        
        # Y position should decrease
        assert new_y < y_position

    def test_handles_optional_address(self, pdf_generator, sample_subject):
        """Test rendering when address is None."""
        sample_subject.address = None
        
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import letter
        
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        y_position = 500
        
        new_y = pdf_generator.render_subject_information(c, sample_subject, y_position)
        
        assert isinstance(new_y, (int, float))

    def test_handles_optional_account_number(self, pdf_generator, sample_subject):
        """Test rendering when account number is None."""
        sample_subject.account_number = None
        
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import letter
        
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        y_position = 500
        
        new_y = pdf_generator.render_subject_information(c, sample_subject, y_position)
        
        assert isinstance(new_y, (int, float))


class TestRenderSuspiciousActivity:
    """Tests for render_suspicious_activity method."""

    def test_renders_activity_dates(self, pdf_generator, sample_activity):
        """Test that activity dates are rendered."""
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import letter
        
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        y_position = 500
        
        new_y = pdf_generator.render_suspicious_activity(c, sample_activity, y_position)
        
        # Y position should decrease
        assert new_y < y_position

    def test_renders_total_amount(self, pdf_generator, sample_activity):
        """Test that total amount is rendered."""
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import letter
        
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        y_position = 500
        
        new_y = pdf_generator.render_suspicious_activity(c, sample_activity, y_position)
        
        assert isinstance(new_y, (int, float))

    def test_renders_multiple_activity_types(self, pdf_generator, sample_activity):
        """Test rendering multiple activity types."""
        sample_activity.activity_type = ["Money Laundering", "Structuring", "Terrorist Financing"]
        
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import letter
        
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        y_position = 500
        
        new_y = pdf_generator.render_suspicious_activity(c, sample_activity, y_position)
        
        # More activity types should consume more vertical space
        assert y_position - new_y > 100


class TestRenderNarrative:
    """Tests for render_narrative method."""

    def test_renders_short_narrative(self, pdf_generator):
        """Test rendering a short narrative."""
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import letter
        
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        y_position = 500
        narrative = "This is a short narrative."
        
        # Should not raise exception
        pdf_generator.render_narrative(c, narrative, y_position)

    def test_handles_long_narrative_with_pagination(self, pdf_generator):
        """Test that long narratives trigger pagination."""
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import letter
        
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        y_position = 200  # Start low to force pagination
        
        # Create long narrative
        long_narrative = " ".join(["This is a test sentence."] * 200)
        
        # Should not raise exception
        pdf_generator.render_narrative(c, long_narrative, y_position)

    def test_wraps_long_lines(self, pdf_generator):
        """Test that long lines are wrapped properly."""
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import letter
        
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        y_position = 500
        
        # Create a very long line without spaces
        long_line = "A" * 200 + " " + "B" * 200
        
        # Should not raise exception
        pdf_generator.render_narrative(c, long_line, y_position)

    def test_handles_empty_narrative(self, pdf_generator):
        """Test rendering empty narrative."""
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import letter
        
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        y_position = 500
        
        # Should not raise exception
        pdf_generator.render_narrative(c, "", y_position)


class TestPDFLayout:
    """Tests for PDF layout constants and structure."""

    def test_initializes_with_letter_size(self, pdf_generator):
        """Test that PDF generator uses letter page size."""
        from reportlab.lib.pagesizes import letter
        
        assert pdf_generator.page_width == letter[0]
        assert pdf_generator.page_height == letter[1]

    def test_has_reasonable_margins(self, pdf_generator):
        """Test that margins are set to reasonable values."""
        assert pdf_generator.margin_left > 0
        assert pdf_generator.margin_right > 0
        assert pdf_generator.margin_top > 0
        assert pdf_generator.margin_bottom > 0

    def test_has_line_height_configured(self, pdf_generator):
        """Test that line height is configured."""
        assert pdf_generator.line_height > 0
        assert pdf_generator.line_height < 30  # Reasonable range


class TestPDFProperties:
    """Property-style tests for PDF correctness guarantees."""

    def test_property_7_pdf_uses_letter_dimensions(self, pdf_generator):
        from reportlab.lib.pagesizes import letter
        assert (pdf_generator.page_width, pdf_generator.page_height) == letter

    def test_property_8_pdf_handles_multi_page_narrative(self, pdf_generator, sample_sar_data):
        PyPDF2 = pytest.importorskip("PyPDF2")
        sample_sar_data.narrative = " ".join(["Suspicious activity details"] * 4000)
        pdf_bytes = pdf_generator.create_sar_pdf(sample_sar_data)
        reader = PyPDF2.PdfReader(BytesIO(pdf_bytes))
        assert len(reader.pages) >= 2

    def test_property_9_pdf_round_trip_validity(self, pdf_generator, sample_sar_data):
        PyPDF2 = pytest.importorskip("PyPDF2")
        pdf_bytes = pdf_generator.create_sar_pdf(sample_sar_data)
        reader = PyPDF2.PdfReader(BytesIO(pdf_bytes))
        assert len(reader.pages) >= 1

    def test_property_32_pdf_section_completeness(self, pdf_generator, sample_sar_data):
        PyPDF2 = pytest.importorskip("PyPDF2")
        pdf_bytes = pdf_generator.create_sar_pdf(sample_sar_data)
        reader = PyPDF2.PdfReader(BytesIO(pdf_bytes))
        text = "\n".join((p.extract_text() or "") for p in reader.pages)
        assert "Subject Information" in text
        assert "Reporting Institution Details" in text
        assert "Suspicious Activity Details" in text
        assert "Narrative" in text

    def test_special_characters_are_sanitized(self, pdf_generator, sample_sar_data):
        sample_sar_data.narrative = "Bad\x00Narrative\\with\fcontrols"
        out = pdf_generator.create_sar_pdf(sample_sar_data)
        assert out.startswith(b"%PDF-")
